# MCU name
MCU = STM32F103

# Bootloader selection
BOOTLOADER = stm32duino

SLEEP_LED_ENABLE = yes  # Breathing sleep LED during USB suspend
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes #RGB MATRIX
RGB_MATRIX_DRIVER = ws2812 #RGB MATRIX
WS2812_DRIVER = pwm #RGB DIVER

